package:
  name: numpy-quaddtype
  version: 1.0.0
  top-level:
    - numpy_quaddtype
source:
  path: numpy_quaddtype-1.0.0
requirements:
  host:
    - numpy
    - libsleef
build:
  script: |
    export CXXFLAGS="${CXXFLAGS} -I${WASM_LIBRARY_DIR}/include -sRELOCATABLE=1";
    export LDFLAGS="${CFLAGS} -L${WASM_LIBRARY_DIR}/lib";
about:
  home: https://github.com/numpy/numpy-quaddtype
  PyPI: https://pypi.org/project/numpy-quaddtype
  summary: Quad (128-bit) float dtype for numpy
  license: BSD-3-Clause
